CREATE USER IF NOT EXISTS ROOT SALT 'c6658411921ee966' HASH 'bfe0efdba5e4f23d4d1c554146d3f6dfcba35d37ca94a4920a031f8e5f46d1de' ADMIN;
CREATE CACHED TABLE PUBLIC.CAR( 
    ID_CAR INT NOT NULL AUTO_INCREMENT,
    MODEL VARCHAR(20), 
    COLOR VARCHAR(20), 
    YEAR VARCHAR(20), 
    ID_MAKER CHAR(18) NOT NULL 
);
ALTER TABLE PUBLIC.CAR ADD CONSTRAINT PUBLIC.XPKCAR PRIMARY KEY(ID_CAR);

CREATE CACHED TABLE PUBLIC.MAKER( 
    ID_MAKER INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20), 
    ADRESS VARCHAR(20), 
    FOUND_YEAR VARCHAR(20) 
);
ALTER TABLE PUBLIC.MAKER ADD CONSTRAINT PUBLIC.XPKMAKER PRIMARY KEY(ID_MAKER);

ALTER TABLE PUBLIC.CAR ADD CONSTRAINT PUBLIC.R_2 FOREIGN KEY(ID_MAKER) REFERENCES PUBLIC.MAKER(ID_MAKER) NOCHECK;